### ISSUE TITLE
Test 384 fails (List.delete_at with invalid positive index) on 32-bit Ubuntu 16.04

### ISSUE THREAD

**Issue by jonathonf** [FascinatedBox/lily#325] opened 2017-07-21 08:45 UTC
Example build log: https://launchpad.net/~jonathonf/+archive/ubuntu/lilylang/+build/13126170/+files/buildlog_ubuntu-xenial-i386.lily_1.1-0york2~16.04_BUILDING.txt.gz

Test run:
```
cd .. && ./pre-commit-tests
384: List.delete_at with invalid positive index. (failed)             
Source:
          test/feature_classes.lily
Expected:
          IndexError: Index 5 is too large for list (maximum: 1)
Received:
          IndexError: Index 5 is too large for list (maximum: 0)

393: List.insert with invalid positive index. (failed)                
Source:
          test/feature_classes.lily
Expected:
          IndexError: Index 5 is too large for list (maximum: 1)
Received:
          IndexError: Index 5 is too large for list (maximum: 0)

543 tests passed, 2 failed, 545 total. 
```

Compiler warnings:

```
make[4]: Entering directory '/build/lily-1.1'
[  3%] Building C object src/CMakeFiles/liblily_obj.dir/st.c.o
/build/lily-1.1/src/st.c: In function 'lily_hash_take':
/build/lily-1.1/src/st.c:190:19: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         raw_key = (char *)search_key->value.integer;
                   ^
/build/lily-1.1/src/st.c: In function 'lily_hash_set':
/build/lily-1.1/src/st.c:234:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         key = (char *)boxed_key->value.integer;
               ^
/build/lily-1.1/src/st.c: In function 'lily_hash_get':
/build/lily-1.1/src/st.c:274:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         key = (char *)boxed_key->value.integer;
               ^

make[4]: Entering directory '/build/lily-1.1/obj-i686-linux-gnu'
[  3%] Building C object src/CMakeFiles/liblily_obj.dir/st.c.o
cd /build/lily-1.1/obj-i686-linux-gnu/src && /usr/bin/i686-linux-gnu-gcc  -DLILY_VERSION_DIR=\"1_1\"  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -O2 -Wall   -fPIC -o CMakeFiles/liblily_obj.dir/st.c.o   -c /build/lily-1.1/src/st.c
/build/lily-1.1/src/st.c: In function 'lily_hash_take':
/build/lily-1.1/src/st.c:190:19: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         raw_key = (char *)search_key->value.integer;
                   ^
/build/lily-1.1/src/st.c: In function 'lily_hash_set':
/build/lily-1.1/src/st.c:234:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         key = (char *)boxed_key->value.integer;
               ^
/build/lily-1.1/src/st.c: In function 'lily_hash_get':
/build/lily-1.1/src/st.c:274:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         key = (char *)boxed_key->value.integer;
               ^
```

All works fine on 64-bit build (no compiler warnings, tests pass).

**Comment by FascinatedBox** [comment] 2017-07-22 05:49
My current machine is a 64-bit one which is why both of these eluded me. I'll grab a 32-bit image later and take a poke at this. I suspect it's something to do with 32-bit truncation. Looks like msgbuf is at least using the right PRI macro for printing.

For the second issue, I think I can fix those warnings by using intptr_t. That code is largely the same as the original implementation, so I haven't touched much of the guts of it.

**Comment by FascinatedBox** [comment] 2017-07-26 19:43
Regarding the compiler warnings about hashes, I've opened #328. Changing out the hash mechanism should get rid of those warnings along the way.

**Comment by jonathonf** [comment] 2017-07-26 20:25
Ah, cool - I didn't know if they were related or not; I included them here as it's only exhibited on the 32-bit build.

**Comment by FascinatedBox** [comment] 2017-07-26 20:36
I'm glad you did though, as it's a nice excuse to potentially condense down the `Hash` creation api.

I managed to reproduce the bug and fix it using `-m32`. I'll leave it to you to close this if it's fixed on your end as well.

**Comment by jonathonf** [comment] 2017-07-27 11:30
Cool. Where are you putting the `-m32` flag, and does it work with the 1.1 release (or do I need to grab newer source)?

With the 1.1 release source I've tried adding this to the CMakeLists.txt: 

```
--- lily-1.1.orig/CMakeLists.txt
+++ lily-1.1/CMakeLists.txt
@@ -10,6 +10,12 @@ if(MSVC)
     set(CMAKE_CTEST_COMMAND	copy lily.exe ..)
 else()
     set(CMAKE_CTEST_COMMAND	cp lily ..)
+
+    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
+        set(CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} -m32")
+        set(CMAKE_LD_FLAGS     "${CMAKE_LD_FLAGS} -m32")
+    endif(CMAKE_SIZEOF_VOID_P EQUAL 4)
+
     if(DEBUG)
         set(CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} -g3")
     endif(DEBUG)
```

which does pass on the `-m32` flag to compiler and linker:

```
[  3%] Building C object src/CMakeFiles/liblily_obj.dir/st.c.o
cd /build/lily-1.1/obj-i686-linux-gnu/src && /usr/bin/i686-linux-gnu-gcc  -DLILY_VERSION_DIR=\"1_1\"  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -m32 -O2 -Wall   -fPIC -o CMakeFiles/liblily_obj.dir/st.c.o   -c /build/lily-1.1/src/st.c
```

```
[ 84%] Linking C shared library ../lib/liblily.so
cd /build/lily-1.1/obj-i686-linux-gnu/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/liblily.dir/link.txt --verbose=1
/usr/bin/i686-linux-gnu-gcc  -fPIC -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -m32 -O2 -Wall  -Wl,-Bsymbolic-functions -Wl,-z,relro -shared -Wl,-soname,liblily.so -o ../lib/liblily.so CMakeFiles/liblily_obj.dir/st.c.o CMakeFiles/liblily_obj.dir/lily_vm.c.o CMakeFiles/liblily_obj.dir/lily_value_stack.c.o CMakeFiles/liblily_obj.dir/lily_utf8.c.o CMakeFiles/liblily_obj.dir/lily_type_system.c.o CMakeFiles/liblily_obj.dir/lily_type_maker.c.o CMakeFiles/liblily_obj.dir/lily_symtab.c.o CMakeFiles/liblily_obj.dir/lily_string_pile.c.o CMakeFiles/liblily_obj.dir/lily_raiser.c.o CMakeFiles/liblily_obj.dir/lily_pkg_time.c.o CMakeFiles/liblily_obj.dir/lily_pkg_sys.c.o CMakeFiles/liblily_obj.dir/lily_pkg_random.c.o CMakeFiles/liblily_obj.dir/lily_pkg_core.c.o CMakeFiles/liblily_obj.dir/lily_pkg_builtin.c.o CMakeFiles/liblily_obj.dir/lily_parser.c.o CMakeFiles/liblily_obj.dir/lily_msgbuf.c.o CMakeFiles/liblily_obj.dir/lily_move.c.o CMakeFiles/liblily_obj.dir/lily_library.c.o CMakeFiles/liblily_obj.dir/lily_lexer.c.o CMakeFiles/liblily_obj.dir/lily_generic_pool.c.o CMakeFiles/liblily_obj.dir/lily_expr.c.o CMakeFiles/liblily_obj.dir/lily_emitter.c.o CMakeFiles/liblily_obj.dir/lily_code_iter.c.o CMakeFiles/liblily_obj.dir/lily_buffer_u16.c.o CMakeFiles/liblily_obj.dir/lily_api_value.c.o CMakeFiles/liblily_obj.dir/lily_alloc.c.o -ldl
```

but the test failure persists. ☹️

**Comment by FascinatedBox** [comment] 2017-07-27 16:25
On my own end I set `-m32` on just the C flags, not the LD flags. I never tested m32 with 1.1, so it's a tossup if that works or not. Right now I can't think of anything else to try against this. :(

**Comment by FascinatedBox** [comment] 2017-07-29 05:48
It occurs to me that the limit on containers is written down as an unsigned 32. I don't see any cases where container limits are written using the plain `%d`. So what happens if you go to get_relative_index in lily_pkg_builtin.c and modify the else if case to:

```
    else if (pos > list_val->num_values) {
        int64_t max_index = list_val->num_values;
        lily_IndexError(s, "Index %ld is too large for list (maximum: %ld)", pos,
                max_index);
    }
```

**Comment by FascinatedBox** [comment] 2017-08-16 22:26
Can you try it again with the latest commit to see if the issue still persists?

**Comment by jonathonf** [comment] 2017-08-18 10:14
Sorry for the delay, I got caught up with other things... :(

I can build successfully for both 32- and 64-bit with the latest commit (https://github.com/FascinatedBox/lily/commit/302db95f37e95b57443df4915a99d27f777ef660).

**Comment by FascinatedBox** [comment] 2017-08-18 23:14
Hey, no problem. I didn't want you to think I'd forgotten about this and hopped over to other issues. Gonna close this as fixed, thanks. :)

**Closed by FascinatedBox** 2017-08-18 23:14 UTC
